"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { loadWebsite } = require("./browser-test-runtime.cjs");
const root = path.resolve(__dirname, "..");
const scripts = (file) => [...fs.readFileSync(path.join(root, file), "utf8")
  .matchAll(/<script[^>]*src="([^"]+)"/g)].map((match) => match[1]);
assert.deepEqual(scripts("index.html"), scripts("frontend/index.html"));
for (const page of ["frontend/index.html", "index.html"]) {
  loadWebsite(page);
  const S = window.IRON_PIT_BROWSER_STATE;
  const K = window.IRON_PIT_BROWSER_HP_THRESHOLD_INSTANT_DEATH;
  const C = window.IRON_PIT_BROWSER_HP_THRESHOLD_CONDITION;
  const template = window.IRON_PIT_BROWSER_HEROES["varek-ashenmark-2014-l17"];
  const member = (id, side, x) => {
    const state = S.buildState(structuredClone(template));
    state.position = { x, y: 0 };
    return { combatant_id: id, side, position_ft: x * 5, state };
  };
  const actor = member("actor", "heroes", 0), target = member("target", "monsters", 1);
  const setup = { ruleset: "2014", heroes: [actor], monsters: [target] };
  target.state.current_hp = 100;
  const kill = template.hp_threshold_instant_death_actions[0];
  const stun = template.hp_threshold_condition_actions[0];
  assert.equal(kill.requiresTargetSight, true);
  assert.equal(stun.requiresTargetSight, true);
  assert.equal(K.legal(actor, target, kill), true);
  target.state.active_effect_ids.push("invisible");
  assert.equal(K.legal(actor, target, kill), false);
  assert.equal(C.legal(actor, target, stun), false);
  actor.state.template.truesight_ft = 60;
  assert.equal(K.legal(actor, target, kill), true);
  assert.equal(C.legal(actor, target, stun), true);
  actor.state.template.truesight_ft = 30;
  const mid = member("mid-target", "monsters", 8);
  mid.state.current_hp = 100;
  mid.state.active_effect_ids.push("invisible");
  assert.equal(K.legal(actor, mid, kill), false);
  actor.state.template.truesight_ft = 60;
  assert.equal(K.legal(actor, mid, kill), true);
  actor.state.template.truesight_ft = 0;
  target.state.active_effect_ids = [];
  actor.state.active_effect_ids.push("blinded");
  assert.equal(K.legal(actor, target, kill), false);
  actor.state.active_effect_ids = [];
  target.state.current_hp = 101;
  assert.equal(K.legal(actor, target, kill), false);
  target.state.current_hp = 150;
  assert.equal(C.legal(actor, target, stun), true);
  target.state.current_hp = 151;
  assert.equal(C.legal(actor, target, stun), false);
  target.state.current_hp = 100;
  window.IRON_PIT_DICE = { roll: () => 10, rollMany: (n) => Array(n).fill(1) };
  const result = window.IRON_PIT_BROWSER_TURN.resolveTurn(1, 1, actor, setup);
  assert.ok(result.events.some((event) => event.feature_id === "power-word-kill"));
  assert.ok(result.events.every((event) => !["hex", "eldritch-blast"].includes(event.feature_id)));
  assert.equal(target.state.is_dead, true);
  assert.equal(actor.state.resources["mystic-arcanum-9"], 0);
  assert.equal(actor.state.resources["spell-slot-5"], 4);
  const owner = member("ward-owner", "heroes", 0), warded = member("warded", "monsters", 1);
  const paladin = Object.values(window.IRON_PIT_BROWSER_HEROES)
    .find((hero) => hero.ruleset === "2014" && hero.class_id === "paladin" && hero.level === 3);
  const sanctuary = paladin.defensive_spell_actions.find((spell) => spell.id === "sanctuary");
  assert.ok(sanctuary);
  const SM = window.IRON_PIT_BROWSER_SPELL_MODIFIERS, T = window.IRON_PIT_BROWSER_TIMED;
  const wardSetup = { heroes: [owner], monsters: [warded] };
  SM.apply(owner.state, [{ targetId: "warded", state: warded.state }], "ward-owner", sanctuary, 0);
  SM.apply(owner.state, [{ targetId: "warded", state: warded.state }], "other", sanctuary, 0);
  T.expireSourceStart(1, 10, owner, wardSetup);
  assert.equal(warded.state.active_modifiers.length, 2);
  T.expireSourceStart(1, 11, owner, wardSetup);
  assert.deepEqual(warded.state.active_modifiers.map((modifier) => modifier.source_id), ["other"]);
  assert.deepEqual(warded.state.timed_effects.map((effect) => effect.source_id), ["other"]);
  assert.deepEqual(window.IRON_PIT_BROWSER_DEFENSIVE_MODIFIERS.removeOwnerAttackEnding(warded.state), ["sanctuary"]);
  assert.deepEqual(warded.state.active_modifiers, []);
  assert.deepEqual(warded.state.timed_effects, []);
  assert.ok(!warded.state.active_effect_ids.includes("sanctuary"));
  assert.deepEqual(S.buildState(structuredClone(template)).active_modifiers, []);
}
console.log("2014 RAW, turn selection, duration and both website entry points passed.");
