from enum import StrEnum


class CombatTrait(StrEnum):
    PACK_TACTICS = "pack-tactics"
    SAVAGE_ATTACKER = "savage-attacker"
    ADRENALINE_RUSH = "adrenaline-rush"
    RELENTLESS_ENDURANCE = "relentless-endurance"
    CHARGE = "charge"
    BLOODIED_FURY = "bloodied-fury"
    SWARM = "swarm"
    UNDEAD_FORTITUDE = "undead-fortitude"
    MAGIC_RESISTANCE = "magic-resistance"
    LIMITED_MAGIC_IMMUNITY = "limited-magic-immunity"
    MAGIC_WEAPONS = "magic-weapons"
    SURE_FOOTED = "sure-footed"
    DARK_DEVOTION = "dark-devotion"
    BRAVE = "brave"
    TWO_HEADED = "two-headed"
    FEY_ANCESTRY = "fey-ancestry"
    AGGRESSIVE = "aggressive"
    CUNNING_ACTION = "cunning-action"
    EVASION = "evasion"
    MARTIAL_ADVANTAGE = "martial-advantage"
    RAMPAGE = "rampage"
    REACTIVE = "reactive"
    LIFE_DOMAIN = "life-domain"
