"""Render current 2014 monster blockers from the authoritative source classifier."""
import argparse
from collections import Counter
import logging
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'backend'))
from app.content.monster_basic_candidates_2014 import basic_blockers_2014, unsupported_traits_2014
from app.content.monster_source_2014 import load_monster_source_2014

OUTPUT = ROOT / 'docs' / 'MONSTER_BLOCKERS_2014.md'
logger = logging.getLogger(__name__)


def render():
    try:
        monsters = load_monster_source_2014()
        blocked = [(monster, basic_blockers_2014(monster)) for monster in monsters if basic_blockers_2014(monster)]
        counts = Counter(blocker for _, blockers in blocked for blocker in blockers)
        rows = ['# Generated 2014 monster blockers', '',
                'Generated by `python scripts/export_monster_fix_list_2014.py`. Do not hand-edit.', '',
                'Read [the fix tracker](MONSTER_FIX_TRACKER.md) for priority, ownership, decisions, and verification.', '',
                f'Source classifier: **{len(monsters) - len(blocked)}/{len(monsters)}** admitted; '
                f'**{len(blocked)}** blocked. This is source classification, not runtime certification.', '',
                'Blocker categories overlap: a monster may require several fixes.', '',
                '| Blocker | Monsters |', '|---|---:|']
        rows += [f'| `{key}` | {count} |' for key, count in counts.most_common()]
        rows += ['', '## Every blocked monster', '',
                 '| Monster | Remaining blockers | Unbound traits |', '|---|---|---|']
        for monster, blockers in sorted(blocked, key=lambda row: row[0].name):
            traits = ', '.join(unsupported_traits_2014(monster)).replace('|', '\\|') or '—'
            rows.append(f'| {monster.name} | {", ".join(blockers)} | {traits} |')
        return '\n'.join(rows) + '\n'
    except Exception:
        logger.exception('Failed to generate 2014 monster fix list.')
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit('2014 monster fix list is stale; regenerate it.')
    else:
        OUTPUT.write_text(rendered)
    print('2014 monster fix list is current.')


if __name__ == '__main__':
    main()
