from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import difflib
import json
import logging
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
COVERAGE = ROOT / "data" / "combat_engine_coverage_v1.json"
JSON_OUTPUT = ROOT / "data" / "universal_mechanic_inventory_v1.json"
MD_OUTPUT = ROOT / "docs" / "UNIVERSAL_MECHANIC_INVENTORY.md"
sys.path.insert(0, str(BACKEND))

from app.content.hero_variant_policy import TARGET_SUBCLASSES  # noqa: E402
from app.content.monster_basic_candidates_2014 import basic_blockers_2014, unsupported_traits_2014  # noqa: E402
from app.content.monster_source_2014 import load_monster_source_2014  # noqa: E402
from app.content.roster_mechanic_requirements import derive_roster_mechanic_requirements  # noqa: E402

logger = logging.getLogger(__name__)


def build_payload() -> dict[str, object]:
    try:
        coverage = json.loads(COVERAGE.read_text(encoding="utf-8"))
        statuses = {item["id"]: item["status"] for item in coverage["capabilities"]}
        hero_requirements = derive_roster_mechanic_requirements(statuses)
        monsters = load_monster_source_2014()
        blocked = [(m, basic_blockers_2014(m)) for m in monsters if basic_blockers_2014(m)]
        ability_monsters: dict[str, list[str]] = defaultdict(list)
        blocker_counts = Counter(blocker for _, blockers in blocked for blocker in blockers)
        for monster, _ in blocked:
            for ability in unsupported_traits_2014(monster):
                ability_monsters[ability].append(monster.name)
        return {
            "schema_version": 1,
            "policy": (
                "Universal behavior is indexed by mechanic id. Source names are presentation/audit metadata. "
                "Homebrew must compose supported universal mechanics and source parameters before any new primitive is considered."
            ),
            "engine": {
                "summary": dict(sorted(Counter(item["status"] for item in coverage["capabilities"]).items())),
                "capabilities": sorted(coverage["capabilities"], key=lambda item: item["id"]),
            },
            "hero_pregen": {
                "roster": {
                    "classes": len(TARGET_SUBCLASSES),
                    "subclasses": sum(len(items) for items in TARGET_SUBCLASSES.values()),
                },
                "summary": dict(sorted(Counter(item.status for item in hero_requirements).items())),
                "mechanics": [
                    {
                        "id": item.id,
                        "kinds": list(item.kinds),
                        "owners": list(item.owners),
                        "demand_count": item.demand_count,
                        "status": item.status,
                    }
                    for item in hero_requirements
                ],
            },
            "monster_2014": {
                "blocked_monster_count": len(blocked),
                "blocker_categories": dict(sorted(blocker_counts.items())),
                "unresolved_printed_abilities": [
                    {"printed_name": name, "demand_count": len(names), "monsters": sorted(names)}
                    for name, names in sorted(ability_monsters.items())
                ],
            },
        }
    except Exception:
        logger.exception("Failed to build universal mechanic inventory.")
        raise


def render_markdown(payload: dict[str, object]) -> str:
    try:
        engine = payload["engine"]
        hero = payload["hero_pregen"]
        monster = payload["monster_2014"]
        summary = ", ".join(f"{key} **{value}**" for key, value in engine["summary"].items())
        rows = [
            "# Universal mechanic inventory", "",
            "Generated by `python scripts/export_universal_mechanic_inventory.py`. Do not hand-edit.", "",
            "This is the lookup surface for monsters, pregens, and future homebrew. **Engine behavior is selected by universal mechanic ID, never by printed ability name.** Source/card data supplies names and parameters.", "",
            "## Workflow", "",
            "1. Look here before searching the roster or writing combat code.",
            "2. Decompose the source ability into semantic mechanics.",
            "3. Reuse one or more `supported` engine capability IDs when they match.",
            "4. If an exact mechanic is absent, record/classify the gap; do not add a source-name resolver.",
            "5. After a binding or primitive is added, regenerate this file. Resolved monster abilities and hero gaps disappear or change status automatically.",
            "6. Homebrew uses the same supported IDs plus source-specific parameters. A new homebrew name does not imply a new engine mechanic.", "",
            "## Engine capability catalog", "",
            f"Capabilities: **{len(engine['capabilities'])}**. {summary}.", "",
            "| Universal mechanic ID | Status | Python | Browser | Tests |",
            "|---|---|---:|---:|---:|",
        ]
        for item in engine["capabilities"]:
            rows.append(f"| `{item['id']}` | {item['status']} | {len(item.get('python', []))} | {len(item.get('browser', []))} | {len(item.get('tests', []))} |")
        rows += ["", "## Hero / pregen open mechanic demand", "",
                 f"Canonical roster: **{hero['roster']['classes']} classes / {hero['roster']['subclasses']} subclasses**. Open entries below exclude supported and arena-out-of-scope mechanics.", "",
                 "| Mechanic ID | Status | Demand | Owners |", "|---|---|---:|---|"]
        for item in hero["mechanics"]:
            if item["status"] not in {"supported", "arena_out_of_scope"}:
                rows.append(f"| `{item['id']}` | {item['status']} | {item['demand_count']} | {', '.join(item['owners'])} |")
        rows += ["", "## 2014 monster unresolved printed abilities", "",
                 f"Blocked monsters: **{monster['blocked_monster_count']}**. These are grouped by printed ability name so the roster never has to be rescanned just to find consumers. Printed names are **not** assumed mechanically equivalent unless an audit proves it.", "",
                 "| Printed ability | Monsters waiting | Count |", "|---|---|---:|"]
        for item in monster["unresolved_printed_abilities"]:
            name = item["printed_name"].replace("|", "\\|")
            rows.append(f"| {name} | {', '.join(item['monsters'])} | {item['demand_count']} |")
        rows += ["", "## Monster blocker categories", "", "| Blocker | Monsters |", "|---|---:|"]
        ordered = sorted(monster["blocker_categories"].items(), key=lambda item: (-item[1], item[0]))
        rows += [f"| `{key}` | {value} |" for key, value in ordered]
        return "\n".join(rows) + "\n"
    except Exception:
        logger.exception("Failed to render universal mechanic inventory markdown.")
        raise


def write_or_check(path: Path, rendered: str, check: bool) -> bool:
    try:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if check and current != rendered:
            print(f"Universal mechanic inventory is stale: {path.relative_to(ROOT)}", file=sys.stderr)
            print("".join(difflib.unified_diff(current.splitlines(True), rendered.splitlines(True),
                                               fromfile="committed", tofile="generated")), file=sys.stderr)
            return False
        if not check:
            path.write_text(rendered, encoding="utf-8")
        return True
    except Exception:
        logger.exception("Failed to write/check universal mechanic inventory: %s", path)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the shared engine/hero/monster mechanic inventory.")
    parser.add_argument("--check", action="store_true", help="Fail if committed inventory outputs are stale.")
    args = parser.parse_args()
    try:
        payload = build_payload()
        json_text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
        markdown = render_markdown(payload)
        ok = write_or_check(JSON_OUTPUT, json_text, args.check) and write_or_check(MD_OUTPUT, markdown, args.check)
        print(f"UNIVERSAL_MECHANIC_INVENTORY engine={len(payload['engine']['capabilities'])} "
              f"hero={len(payload['hero_pregen']['mechanics'])} "
              f"monster_abilities={len(payload['monster_2014']['unresolved_printed_abilities'])}")
        return 0 if ok else 1
    except Exception:
        logger.exception("Universal mechanic inventory export failed.")
        return 1


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    raise SystemExit(main())
