from __future__ import annotations

from collections import Counter, defaultdict
import json
import logging
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
COVERAGE = ROOT / "data" / "combat_engine_coverage_v1.json"
sys.path.insert(0, str(BACKEND))

from app.content.hero_variant_policy import TARGET_SUBCLASSES  # noqa: E402
from app.content.monster_basic_candidates_2014 import basic_blockers_2014, unsupported_traits_2014  # noqa: E402
from app.content.monster_source_2014 import load_monster_source_2014  # noqa: E402
from app.content.roster_mechanic_requirements import derive_roster_mechanic_requirements  # noqa: E402

logger = logging.getLogger(__name__)


def build_payload() -> dict[str, object]:
    try:
        coverage = json.loads(COVERAGE.read_text(encoding="utf-8"))
        statuses = {item["id"]: item["status"] for item in coverage["capabilities"]}
        hero_requirements = derive_roster_mechanic_requirements(statuses)
        monsters = load_monster_source_2014()
        blocked = [(m, basic_blockers_2014(m)) for m in monsters if basic_blockers_2014(m)]
        ability_monsters: dict[str, list[str]] = defaultdict(list)
        blocker_counts = Counter(blocker for _, blockers in blocked for blocker in blockers)
        for monster, _ in blocked:
            for ability in unsupported_traits_2014(monster):
                ability_monsters[ability].append(monster.name)
        return {
            "schema_version": 1,
            "policy": (
                "Universal behavior is indexed by mechanic id. Complete source-specific abilities remain authoritative source data. "
                "Homebrew and unique monster abilities compose supported universal mechanics plus source parameters; "
                "only a genuinely new semantic remainder justifies a new reusable primitive."
            ),
            "engine": {
                "summary": dict(sorted(Counter(item["status"] for item in coverage["capabilities"]).items())),
                "capabilities": sorted(coverage["capabilities"], key=lambda item: item["id"]),
            },
            "hero_pregen": {
                "roster": {
                    "classes": len(TARGET_SUBCLASSES),
                    "subclasses": sum(len(items) for items in TARGET_SUBCLASSES.values()),
                },
                "summary": dict(sorted(Counter(item.status for item in hero_requirements).items())),
                "mechanics": [
                    {
                        "id": item.id,
                        "kinds": list(item.kinds),
                        "owners": list(item.owners),
                        "demand_count": item.demand_count,
                        "status": item.status,
                    }
                    for item in hero_requirements
                ],
            },
            "monster_2014": {
                "blocked_monster_count": len(blocked),
                "blocker_categories": dict(sorted(blocker_counts.items())),
                "unresolved_printed_abilities": [
                    {"printed_name": name, "demand_count": len(names), "monsters": sorted(names)}
                    for name, names in sorted(ability_monsters.items())
                ],
            },
        }
    except Exception:
        logger.exception("Failed to build universal mechanic inventory.")
        raise


def render_markdown(payload: dict[str, object]) -> str:
    try:
        engine = payload["engine"]
        hero = payload["hero_pregen"]
        monster = payload["monster_2014"]
        summary = ", ".join(f"{key} **{value}**" for key, value in engine["summary"].items())
        rows = [
            "# Universal mechanic inventory", "",
            "Generated by `python scripts/export_universal_mechanic_inventory.py`. Do not hand-edit.", "",
            "This is the lookup surface for monsters, pregens, and future homebrew. **Engine behavior is selected by universal mechanic ID, never by printed ability name.** Complete source-specific abilities remain on their source/card; the engine supplies their reusable underlying behavior.", "",
            "## Workflow", "",
            "1. Look here before searching the roster or writing combat code.",
            "2. Decompose the source ability into semantic mechanics.",
            "3. Reuse one or more `supported` engine capability IDs when they match.",
            "4. If an exact mechanic is absent, record/classify the gap; do not add a source-name resolver.",
            "5. After a binding or primitive is added, regenerate this file. Resolved monster abilities and hero gaps disappear or change status automatically.",
            "6. Preserve every complete source ability, including unique monster/homebrew abilities. Bind existing primitives for matching behavior; if a semantic remainder is truly new, add the smallest reusable primitive and bind the source ability to it.", "",
            "## Engine capability catalog", "",
            f"Capabilities: **{len(engine['capabilities'])}**. {summary}.", "",
            "| Universal mechanic ID | Status | Python | Browser | Tests |",
            "|---|---|---:|---:|---:|",
        ]
        for item in engine["capabilities"]:
            rows.append(
                f"| `{item['id']}` | {item['status']} | {len(item.get('python', []))} | "
                f"{len(item.get('browser', []))} | {len(item.get('tests', []))} |"
            )
        rows += ["", "## Hero / pregen open mechanic demand", "",
                 f"Canonical roster: **{hero['roster']['classes']} classes / {hero['roster']['subclasses']} subclasses**. Open entries below exclude supported and arena-out-of-scope mechanics.", "",
                 "| Mechanic ID | Status | Demand | Owners |", "|---|---|---:|---|"]
        for item in hero["mechanics"]:
            if item["status"] not in {"supported", "arena_out_of_scope"}:
                rows.append(
                    f"| `{item['id']}` | {item['status']} | {item['demand_count']} | "
                    f"{', '.join(item['owners'])} |"
                )
        rows += ["", "## 2014 monster unresolved printed abilities", "",
                 f"Blocked monsters: **{monster['blocked_monster_count']}**. These are grouped by printed ability name so the roster never has to be rescanned just to find consumers. Printed names are **not** assumed mechanically equivalent unless an audit proves it.", "",
                 "| Printed ability | Monsters waiting | Count |", "|---|---|---:|"]
        for item in monster["unresolved_printed_abilities"]:
            name = item["printed_name"].replace("|", "\\|")
            rows.append(f"| {name} | {', '.join(item['monsters'])} | {item['demand_count']} |")
        rows += ["", "## Monster blocker categories", "", "| Blocker | Monsters |", "|---|---:|"]
        ordered = sorted(monster["blocker_categories"].items(), key=lambda item: (-item[1], item[0]))
        rows += [f"| `{key}` | {value} |" for key, value in ordered]
        return "\n".join(rows) + "\n"
    except Exception:
        logger.exception("Failed to render universal mechanic inventory markdown.")
        raise
